import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, Pressable, View } from 'react-native';
import { Button, Card, Field, Page, SectionTitle, Txt, useColors } from '@/components/ui';
import { searchFoods } from '@/services/foodService';
import { useApp } from '@/store/AppProvider';
import { dateKey } from '@/services/date';
import type { Food, MealEntry, MealType } from '@/types';

const mealTypes:MealType[]=['Desayuno','Media mañana','Comida','Merienda','Cena','Otros'];
export default function AddFoodScreen(){
 const params=useLocalSearchParams<{foodId?:string;mealId?:string}>();
 const {foods,meals,addMeal,addFood,updateMeal,deleteMeal,toggleFavorite}=useApp();const colors=useColors();
 const editing=params.mealId?meals.find(m=>m.id===params.mealId):undefined;
 const initialSelected=editing?{id:editing.foodId,name:editing.name,calories:editing.calories*100/editing.quantity,protein:editing.protein*100/editing.quantity,carbs:editing.carbs*100/editing.quantity,fat:editing.fat*100/editing.quantity,favorite:false,custom:false}:foods.find(f=>f.id===params.foodId)??null;
 const [query,setQuery]=useState('');const [selected,setSelected]=useState<Food|null>(initialSelected);const [quantity,setQuantity]=useState(String(editing?.quantity??100));const [unit,setUnit]=useState<'g'|'porción'>(editing?.unit??'g');const [mealType,setMealType]=useState<MealType>(editing?.mealType??'Comida');const [custom,setCustom]=useState(false);const [customName,setCustomName]=useState('');const [cal,setCal]=useState('');const [protein,setProtein]=useState('');const [carbs,setCarbs]=useState('');const [fat,setFat]=useState('');
 const results=useMemo(()=>searchFoods(foods,query).slice(0,7),[foods,query]);
 const factor=(Number(quantity)||0)/100;const nutrition=selected?{calories:selected.calories*factor,protein:selected.protein*factor,carbs:selected.carbs*factor,fat:selected.fat*factor}:{calories:(Number(cal)||0)*factor,protein:(Number(protein)||0)*factor,carbs:(Number(carbs)||0)*factor,fat:(Number(fat)||0)*factor};
 const save=async()=>{const name=custom?customName.trim():selected?.name;if(!name){Alert.alert('Falta el alimento','Elige un alimento o crea uno personalizado.');return;}const q=Number(quantity);if(!Number.isFinite(q)||q<=0||q>5000){Alert.alert('Cantidad no válida','La cantidad debe estar entre 1 y 5.000.');return;}if(custom&&[cal,protein,carbs,fat].some(v=>!Number.isFinite(Number(v))||Number(v)<0||Number(v)>1000)){Alert.alert('Revisa los valores','Calorías y macros deben ser números positivos por 100 g.');return;}let food=selected;if(custom){food={id:editing?.foodId??`custom-${Date.now()}`,name,calories:Number(cal),protein:Number(protein),carbs:Number(carbs),fat:Number(fat),favorite:false,custom:true};await addFood(food);}if(!food)return;const entry:MealEntry={id:editing?.id??`meal-${Date.now()}`,foodId:food.id,name,mealType,date:editing?.date??dateKey(),quantity:q,unit,calories:food.calories*factor,protein:food.protein*factor,carbs:food.carbs*factor,fat:food.fat*factor};if(editing)await updateMeal(entry);else await addMeal(entry);router.back();};
 return <Page><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Pressable accessibilityRole="button" onPress={()=>router.back()}><Txt style={{color:colors.primary,fontWeight:'700'}}>‹  Volver</Txt></Pressable><Txt style={{fontSize:19,fontWeight:'800'}}>{editing?'Editar comida':'Añadir comida'}</Txt><View style={{width:50}}/></View>
 {!selected&&!custom&&<><Field label="Buscar alimento" value={query} onChangeText={setQuery} placeholder="Ej. avena, plátano…"/><SectionTitle>Alimentos disponibles</SectionTitle>{results.map(food=><Pressable key={food.id} onPress={()=>setSelected(food)}><Card style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:13}}><Txt style={{fontWeight:'700'}}>{food.name}{food.favorite?'  ★':''}</Txt><View style={{flexDirection:'row',alignItems:'center',gap:10}}><Txt style={{color:colors.muted}}>{food.calories} kcal / 100 g</Txt><Pressable accessibilityRole="button" accessibilityLabel={food.favorite?'Quitar de favoritos':'Guardar en favoritos'} onPress={()=>toggleFavorite(food.id)}><Txt style={{fontSize:18,color:colors.accent}}>{food.favorite?'★':'☆'}</Txt></Pressable></View></Card></Pressable>)}<Button title="＋ Crear alimento personalizado" secondary onPress={()=>setCustom(true)}/></>}
 {(selected||custom)&&<><Card><Txt style={{fontSize:20,fontWeight:'800'}}>{custom?'Nuevo alimento':selected?.name}</Txt>{custom&&<><Field label="Nombre" value={customName} onChangeText={setCustomName} placeholder="Nombre del alimento"/><Field label="Calorías por 100 g" value={cal} onChangeText={setCal} keyboardType="decimal-pad"/><View style={{flexDirection:'row',gap:9}}><View style={{flex:1}}><Field label="Proteína (g)" value={protein} onChangeText={setProtein} keyboardType="decimal-pad"/></View><View style={{flex:1}}><Field label="Carbohidratos (g)" value={carbs} onChangeText={setCarbs} keyboardType="decimal-pad"/></View></View><Field label="Grasas (g)" value={fat} onChangeText={setFat} keyboardType="decimal-pad"/></>}
 <Field label="Cantidad" value={quantity} onChangeText={setQuantity} keyboardType="decimal-pad"/><View style={{flexDirection:'row',gap:9}}><Pressable onPress={()=>setUnit('g')} style={{backgroundColor:unit==='g'?colors.soft:colors.background,padding:10,borderRadius:12}}><Txt>Gramos</Txt></Pressable><Pressable onPress={()=>setUnit('porción')} style={{backgroundColor:unit==='porción'?colors.soft:colors.background,padding:10,borderRadius:12}}><Txt>Porción</Txt></Pressable></View>
 <Txt style={{fontWeight:'700'}}>Comida</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}>{mealTypes.map(type=><Pressable key={type} onPress={()=>setMealType(type)} style={{backgroundColor:mealType===type?colors.primary:colors.soft,paddingHorizontal:11,paddingVertical:8,borderRadius:18}}><Txt style={{color:mealType===type?'#fff':colors.primary,fontSize:12,fontWeight:'600'}}>{type}</Txt></Pressable>)}</View>
 <Txt style={{color:colors.muted}}>≈ {Math.round(nutrition.calories)} kcal · P {Math.round(nutrition.protein)} g · C {Math.round(nutrition.carbs)} g · G {Math.round(nutrition.fat)} g</Txt></Card><Button title={editing?'Guardar cambios':'Añadir al día'} onPress={save}/>{editing&&<Button title="Eliminar comida" secondary onPress={()=>Alert.alert('Eliminar comida','¿Quieres eliminar este registro?', [{text:'Cancelar',style:'cancel'},{text:'Eliminar',style:'destructive',onPress:async()=>{await deleteMeal(editing.id);router.back();}}])}/>}<Button title="Elegir otro alimento" secondary onPress={()=>{setSelected(null);setCustom(false)}}/></>}
 </Page>;
}
