import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, View } from 'react-native';
import { Button, Card, Field, Page, Txt, useColors, styles } from '@/components/ui';
import { useApp } from '@/store/AppProvider';
import { calculateCalorieTarget, calculateMacrosTarget, calculateTDEE, validateProfileField } from '@/services/nutrition';
import type { Activity, Goal, Profile, Sex } from '@/types';

const steps = ['¡Hola!', 'Tu cuerpo', 'Tu actividad', 'Tu objetivo'];
function Choice({ label, selected, onPress }: {label:string; selected:boolean; onPress:()=>void}) {
 const colors=useColors(); return <Pressable accessibilityRole="radio" accessibilityState={{checked:selected}} onPress={onPress} style={{padding:15,borderRadius:15,borderWidth:1,borderColor:selected?colors.primary:colors.line,backgroundColor:selected?colors.soft:colors.surface}}><Txt style={{fontWeight:selected?'700':'500'}}>{label}</Txt></Pressable>;
}
export default function OnboardingScreen() {
 const { saveProfile }=useApp(); const themeColors=useColors(); const [step,setStep]=useState(0); const [name,setName]=useState(''); const [sex,setSex]=useState<Sex>('female'); const [age,setAge]=useState('30'); const [height,setHeight]=useState('168'); const [weight,setWeight]=useState('70'); const [target,setTarget]=useState('65'); const [activity,setActivity]=useState<Activity>('moderate'); const [goal,setGoal]=useState<Goal>('lose');
 const validate=()=>{ if(step===1){for(const [field,value] of [['age',Number(age)],['heightCm',Number(height)],['weightKg',Number(weight)],['targetWeightKg',Number(target)]] as const){const error=validateProfileField(field,value);if(error){Alert.alert('Revisa tus datos',error);return false;}}} return true;};
 const next=async()=>{if(!validate())return;if(step<3){setStep(step+1);return;}const input={sex,age:Number(age),heightCm:Number(height),weightKg:Number(weight),targetWeightKg:Number(target),activity,goal};const calories=calculateCalorieTarget(calculateTDEE(input),goal);const profile:Profile={...input,name:name.trim(),calorieTarget:calories,macros:calculateMacrosTarget(calories,Number(weight),goal),units:'metric'};await saveProfile(profile);router.replace('/(tabs)');};
 return <Page style={{flexGrow:1,justifyContent:'space-between',paddingTop:36}}><View style={{gap:25}}><View style={{gap:10}}><Txt style={{fontSize:14,fontWeight:'700',color:themeColors.primary}}>CALTRACKER · {step+1} DE 4</Txt><View style={{height:5,backgroundColor:themeColors.line,borderRadius:5}}><View style={{height:5,width:`${((step+1)/4)*100}%`,backgroundColor:themeColors.primary,borderRadius:5}} /></View><Txt style={{fontSize:32,fontWeight:'800',marginTop:15}}>{steps[step]}</Txt><Txt style={{color:themeColors.muted,fontSize:15}}>{['Vamos a crear un plan que encaje contigo. Solo te llevará un minuto.','Con estos datos estimaremos tus necesidades diarias.','Cuéntanos cómo suele ser un día normal.','Cada objetivo es personal. Los resultados son estimaciones.'][step]}</Txt></View>
 {step===0&&<Card><Txt style={{fontSize:48}}>🌿</Txt><Field label="¿Cómo te llamamos? (opcional)" value={name} onChangeText={setName} placeholder="Tu nombre o apodo" autoCapitalize="words"/><Txt style={{color:themeColors.muted}}>Tu información se guarda solo en este dispositivo.</Txt></Card>}
 {step===1&&<Card><Txt style={styles.label}>Sexo para estimar el metabolismo</Txt><View style={{gap:9}}><Choice label="Mujer" selected={sex==='female'} onPress={()=>setSex('female')}/><Choice label="Hombre" selected={sex==='male'} onPress={()=>setSex('male')}/><Choice label="Prefiero no especificar" selected={sex==='other'} onPress={()=>setSex('other')}/></View><Field label="Edad (años)" value={age} onChangeText={setAge} keyboardType="number-pad"/><Field label="Altura (cm)" value={height} onChangeText={setHeight} keyboardType="decimal-pad"/><Field label="Peso actual (kg)" value={weight} onChangeText={setWeight} keyboardType="decimal-pad"/><Field label="Peso objetivo (kg)" value={target} onChangeText={setTarget} keyboardType="decimal-pad"/></Card>}
 {step===2&&<Card><Txt style={styles.label}>¿Cuál describe mejor tu actividad?</Txt>{([['sedentary','Poco activo','Trabajo sentado y poco ejercicio'],['light','Algo activo','Ejercicio ligero 1–3 días/semana'],['moderate','Moderadamente activo','Ejercicio 3–5 días/semana'],['active','Muy activo','Ejercicio intenso 6–7 días/semana'],['veryActive','Extremadamente activo','Entrenamiento y actividad física diaria']] as [Activity,string,string][]).map(([value,label,desc])=><Pressable key={value} accessibilityRole="radio" accessibilityState={{checked:activity===value}} onPress={()=>setActivity(value)} style={{padding:13,borderRadius:14,borderWidth:1,borderColor:activity===value?themeColors.primary:themeColors.line,backgroundColor:activity===value?themeColors.soft:themeColors.surface}}><Txt style={{fontWeight:'700'}}>{label}</Txt><Txt style={{color:themeColors.muted,fontSize:13,marginTop:3}}>{desc}</Txt></Pressable>)}</Card>}
 {step===3&&<Card><Txt style={styles.label}>¿Qué te gustaría conseguir?</Txt>{([['lose','Perder peso','Déficit moderado, sin restricciones extremas'],['define','Definir','Déficit suave para acompañar tu entrenamiento'],['maintain','Mantener peso','Una referencia cercana a tu gasto estimado']] as [Goal,string,string][]).map(([value,label,desc])=><Pressable key={value} accessibilityRole="radio" accessibilityState={{checked:goal===value}} onPress={()=>setGoal(value)} style={{padding:15,borderRadius:15,borderWidth:1,borderColor:goal===value?themeColors.primary:themeColors.line,backgroundColor:goal===value?themeColors.soft:themeColors.surface}}><Txt style={{fontWeight:'700'}}>{label}</Txt><Txt style={{color:themeColors.muted,fontSize:13,marginTop:3}}>{desc}</Txt></Pressable>)}<Txt style={{fontSize:12,color:themeColors.muted}}>Las calorías son una estimación orientativa, no una prescripción médica. Las necesidades reales varían entre personas.</Txt></Card>}
 </View><View style={{gap:10}}><Button title={step===3?'Crear mi plan':'Continuar'} onPress={next}/>{step>0&&<Button title="Volver" secondary onPress={()=>setStep(step-1)}/>}</View></Page>;
}
