import { useMemo, useState } from 'react';
import { Pressable, View } from 'react-native';
import { Card, Page, SectionTitle, Txt, useColors } from '@/components/ui';
import { useApp } from '@/store/AppProvider';
import { dateKey } from '@/services/date';

export default function History(){const {meals,profile}=useApp();const colors=useColors();const [day,setDay]=useState(new Date());const key=dateKey(day);const entries=useMemo(()=>meals.filter(m=>m.date===key),[meals,key]);const totals=entries.reduce((s,m)=>({cal:s.cal+m.calories,p:s.p+m.protein,c:s.c+m.carbs,f:s.f+m.fat}),{cal:0,p:0,c:0,f:0});const shift=(d:number)=>setDay(prev=>new Date(prev.getFullYear(),prev.getMonth(),prev.getDate()+d));
 return <Page><Txt style={{fontSize:29,fontWeight:'800'}}>Historial</Txt><Card style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Pressable accessibilityLabel="Día anterior" onPress={()=>shift(-1)}><Txt style={{fontSize:24,color:colors.primary}}>‹</Txt></Pressable><View style={{alignItems:'center'}}><Txt style={{fontWeight:'700',textTransform:'capitalize'}}>{day.toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'})}</Txt><Txt style={{fontSize:12,color:colors.muted}}>{key===dateKey()?'Hoy':''}</Txt></View><Pressable accessibilityLabel="Día siguiente" onPress={()=>shift(1)} disabled={key>=dateKey()}><Txt style={{fontSize:24,color:key>=dateKey()?colors.line:colors.primary}}>›</Txt></Pressable></Card><Card><Txt style={{fontSize:27,fontWeight:'800'}}>{Math.round(totals.cal)} kcal</Txt><Txt style={{color:colors.muted}}>Objetivo {profile?.calorieTarget??0} · diferencia {Math.round((profile?.calorieTarget??0)-totals.cal)} kcal</Txt><Txt>Proteína {Math.round(totals.p)} g · Carbohidratos {Math.round(totals.c)} g · Grasas {Math.round(totals.f)} g</Txt></Card><SectionTitle>Comidas</SectionTitle>{entries.length===0?<Card><Txt style={{color:colors.muted}}>No hay comidas registradas este día.</Txt></Card>:entries.map(entry=><Card key={entry.id} style={{flexDirection:'row',justifyContent:'space-between'}}><View><Txt style={{fontWeight:'700'}}>{entry.name}</Txt><Txt style={{color:colors.muted,fontSize:12}}>{entry.mealType}</Txt></View><Txt style={{fontWeight:'700'}}>{Math.round(entry.calories)} kcal</Txt></Card>)}</Page>;
}
