import { router } from 'expo-router';
import { useMemo } from 'react';
import { Pressable, View } from 'react-native';
import { Button, Card, Page, SectionTitle, Txt, useColors } from '@/components/ui';
import { useApp } from '@/store/AppProvider';
import type { MealEntry } from '@/types';
import { dateKey } from '@/services/date';
export default function Dashboard() {
 const {profile,meals,foods}=useApp();const colors=useColors();
 const today=useMemo(()=>meals.filter((m)=>m.date===dateKey()),[meals]);
 const totals=today.reduce((sum,m)=>({calories:sum.calories+m.calories,protein:sum.protein+m.protein,carbs:sum.carbs+m.carbs,fat:sum.fat+m.fat}),{calories:0,protein:0,carbs:0,fat:0});
 const target=profile?.calorieTarget??2000;const remaining=target-totals.calories;const ratio=Math.min(100,Math.round(totals.calories/target*100));
 const greeting=new Date().toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'});
 const recent=foods.filter(f=>meals.some(m=>m.foodId===f.id)).slice(0,4);
 return <Page><View style={{gap:4,marginTop:8}}><Txt style={{fontSize:14,color:colors.muted,textTransform:'capitalize'}}>{greeting}</Txt><Txt style={{fontSize:29,fontWeight:'800'}}>Hola{profile?.name?`, ${profile.name}`:''} 👋</Txt><Txt style={{fontSize:14,color:colors.muted}}>Hoy es un buen día para cuidarte.</Txt></View>
 <Card style={{backgroundColor:colors.primary,borderColor:colors.primary,padding:22}}><Txt style={{color:'#FFFFFF',opacity:.8,fontWeight:'600'}}>TE QUEDAN</Txt><View style={{flexDirection:'row',alignItems:'baseline',gap:6}}><Txt accessibilityLabel={`${Math.max(0,remaining)} calorías restantes`} style={{fontSize:45,fontWeight:'800',color:'#FFFFFF'}}>{Math.max(0,remaining).toLocaleString('es-ES')}</Txt><Txt style={{color:'#FFFFFF',opacity:.85}}>kcal</Txt></View><View style={{height:9,backgroundColor:'rgba(255,255,255,.28)',borderRadius:8,overflow:'hidden'}}><View style={{height:9,width:`${ratio}%`,backgroundColor:'#FFFFFF',borderRadius:8}}/></View><View style={{flexDirection:'row',justifyContent:'space-between'}}><Txt style={{color:'#FFFFFF'}}>Consumidas {totals.calories} kcal</Txt><Txt style={{color:'#FFFFFF'}}>Objetivo {target}</Txt></View><Txt style={{color:'#FFFFFF',opacity:.8,fontSize:12}}>Objetivo orientativo · {profile?.goal==='maintain'?'Mantener':profile?.goal==='define'?'Definir':'Perder peso'}</Txt></Card>
 <Card><SectionTitle>Macronutrientes</SectionTitle><View style={{flexDirection:'row',justifyContent:'space-between'}}>{([['Proteína',totals.protein,profile?.macros.protein??0,colors.primary],['Carbos',totals.carbs,profile?.macros.carbs??0,colors.accent],['Grasas',totals.fat,profile?.macros.fat??0,'#8E8BC9']] as [string,number,number,string][]).map(([label,value,max,color])=><View key={label} style={{gap:5}}><Txt style={{fontSize:12,color:colors.muted}}>{label}</Txt><Txt style={{fontSize:17,fontWeight:'700'}}>{Math.round(value)}<Txt style={{fontSize:12,color:colors.muted}}> / {max} g</Txt></Txt><View style={{height:4,width:78,backgroundColor:colors.line,borderRadius:5}}><View style={{height:4,width:`${Math.min(100,max?value/max*100:0)}%`,backgroundColor:color,borderRadius:5}}/></View></View>)}</View></Card>
 <SectionTitle>Comidas de hoy</SectionTitle>
 {today.length===0?<Card><Txt style={{fontSize:15,fontWeight:'700'}}>Tu día empieza aquí</Txt><Txt style={{color:colors.muted}}>Añade tu primera comida y lleva el control sin complicaciones.</Txt></Card>:today.map((meal)=> <MealRow key={meal.id} meal={meal} onPress={()=>router.push({pathname:'/add-food',params:{mealId:meal.id}})}/>)}
 {recent.length>0&&<><SectionTitle>Usados recientemente</SectionTitle><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{recent.map(food=><Pressable key={food.id} onPress={()=>router.push({pathname:'/add-food',params:{foodId:food.id}})} style={{backgroundColor:colors.soft,paddingHorizontal:13,paddingVertical:9,borderRadius:20}}><Txt style={{color:colors.primary,fontWeight:'600'}}>{food.name}</Txt></Pressable>)}</View></>}
 <Button title="＋  Añadir comida" onPress={()=>router.push('/add-food')}/><Txt style={{fontSize:11,color:colors.muted,textAlign:'center'}}>Las calorías son estimaciones y no sustituyen orientación profesional.</Txt></Page>;
}
function MealRow({meal,onPress}:{meal:MealEntry;onPress:()=>void}) {const colors=useColors();return <Pressable onPress={onPress} accessibilityRole="button" accessibilityLabel={`Editar ${meal.name}, ${meal.calories} kilocalorías`}><Card style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:14}}><View><Txt style={{fontWeight:'700'}}>{meal.name}</Txt><Txt style={{fontSize:12,color:colors.muted}}>{meal.mealType} · {meal.quantity} {meal.unit}</Txt></View><Txt style={{fontWeight:'700'}}>{Math.round(meal.calories)} kcal</Txt></Card></Pressable>;}
