import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, Pressable, View } from 'react-native';
import { Button, Card, Field, Page, SectionTitle, Txt, useColors } from '@/components/ui';
import { calculateCalorieTarget, calculateMacroTargets, calculateTDEE, validateProfileField } from '@/services/nutrition';
import type { Activity, Goal, Sex, ThemeMode } from '@/types';
import { useApp } from '@/store/AppProvider';
import { dateKey } from '@/services/date';

export default function Profile(){const {profile,meals,weights,theme,saveProfile,setTheme,clearAll}=useApp();const colors=useColors();const [calories,setCalories]=useState(String(profile?.calorieTarget??''));const [name,setName]=useState(profile?.name??'');const [age,setAge]=useState(String(profile?.age??''));const [height,setHeight]=useState(String(profile?.heightCm??''));const [weight,setWeight]=useState(String(profile?.weightKg??''));const [targetWeight,setTargetWeight]=useState(String(profile?.targetWeightKg??''));const [sex,setSex]=useState<Sex>(profile?.sex??'female');const [activity,setActivity]=useState<Activity>(profile?.activity??'moderate');const [selectedGoal,setSelectedGoal]=useState<Goal>(profile?.goal??'lose');const [protein,setProtein]=useState(String(profile?.macros.protein??''));const [carbs,setCarbs]=useState(String(profile?.macros.carbs??''));const [fat,setFat]=useState(String(profile?.macros.fat??''));
 const days7=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-i);return dateKey(d)}),[]);const days30=useMemo(()=>Array.from({length:30},(_,i)=>{const d=new Date();d.setDate(d.getDate()-i);return dateKey(d)}),[]);const avg=(days:string[])=>{const daily=days.map(day=>meals.filter(m=>m.date===day).reduce((sum,m)=>sum+m.calories,0)).filter(v=>v>0);return daily.length?Math.round(daily.reduce((a,b)=>a+b,0)/daily.length):0};const logged=new Set(meals.map(m=>m.date));const adherence=profile?Math.round([...logged].filter(day=>Math.abs(meals.filter(m=>m.date===day).reduce((s,m)=>s+m.calories,0)-profile.calorieTarget)<=profile.calorieTarget*.1).length/Math.max(logged.size,1)*100):0;
 const save=async()=>{if(!profile)return;const target=Number(calories);const error=validateProfileField('calorieTarget',target);if(error){Alert.alert('Objetivo no válido',error);return;}const macros={protein:Number(protein),carbs:Number(carbs),fat:Number(fat)};if(Object.values(macros).some(v=>!Number.isFinite(v)||v<0||v>1000)){Alert.alert('Macros no válidos','Introduce valores de macros entre 0 y 1.000 g.');return;}const profileError=validateProfileField('age',Number(age))??validateProfileField('heightCm',Number(height))??validateProfileField('weightKg',Number(weight))??validateProfileField('targetWeightKg',Number(targetWeight));if(profileError){Alert.alert('Revisa tus datos',profileError);return;}await saveProfile({...profile,name:name.trim(),age:Number(age),heightCm:Number(height),weightKg:Number(weight),targetWeightKg:Number(targetWeight),sex,activity,goal:selectedGoal,calorieTarget:target,macros});Alert.alert('Guardado','Tu perfil se ha actualizado.');};
 const setGoal=(goal:Goal)=>{if(!profile)return;setSelectedGoal(goal);const basis={sex,age:Number(age),heightCm:Number(height),weightKg:Number(weight),activity};const target=calculateCalorieTarget(calculateTDEE(basis),goal);const macros=calculateMacroTargets(target,Number(weight),goal);setCalories(String(target));setProtein(String(macros.protein));setCarbs(String(macros.carbs));setFat(String(macros.fat));};
 const remove=()=>Alert.alert('Borrar todos los datos','Se eliminarán perfil, alimentos, comidas e historial de peso. Esta acción no se puede deshacer.',[{text:'Cancelar',style:'cancel'},{text:'Borrar datos',style:'destructive',onPress:async()=>{await clearAll();router.replace('/onboarding');}}]);
 return <Page><Txt style={{fontSize:29,fontWeight:'800'}}>Perfil</Txt><SectionTitle>Estadísticas</SectionTitle><View style={{flexDirection:'row',gap:10}}>{[['7 días',avg(days7)],['30 días',avg(days30)]].map(([label,value])=><Card key={String(label)} style={{flex:1}}><Txt style={{fontSize:12,color:colors.muted}}>Promedio {label}</Txt><Txt style={{fontSize:21,fontWeight:'800'}}>{value} kcal</Txt></Card>)}</View><Card><Txt>Días registrados: {logged.size}</Txt><Txt>Peso medio: {weights.length?`${(weights.reduce((s,w)=>s+w.weightKg,0)/weights.length).toFixed(1)} kg`:'Sin registros'}</Txt><Txt>Adherencia aproximada: {adherence}%</Txt></Card>
 <SectionTitle>Datos personales</SectionTitle><Field label="Nombre" value={name} onChangeText={setName} placeholder="Nombre o apodo"/><View style={{flexDirection:'row',gap:10}}><View style={{flex:1}}><Field label="Edad (años)" value={age} onChangeText={setAge} keyboardType="number-pad"/></View><View style={{flex:1}}><Field label="Altura (cm)" value={height} onChangeText={setHeight} keyboardType="decimal-pad"/></View></View><View style={{flexDirection:'row',gap:10}}><View style={{flex:1}}><Field label="Peso actual (kg)" value={weight} onChangeText={setWeight} keyboardType="decimal-pad"/></View><View style={{flex:1}}><Field label="Peso objetivo (kg)" value={targetWeight} onChangeText={setTargetWeight} keyboardType="decimal-pad"/></View></View><Txt style={{fontWeight:'700'}}>Sexo</Txt><View style={{flexDirection:'row',gap:8}}>{([['female','Mujer'],['male','Hombre'],['other','No especificar']] as [Sex,string][]).map(([value,label])=><Pressable key={value} onPress={()=>setSex(value)} style={{flex:1,alignItems:'center',padding:10,borderRadius:14,backgroundColor:sex===value?colors.primary:colors.soft}}><Txt style={{fontSize:11,fontWeight:'700',color:sex===value?'#fff':colors.primary}}>{label}</Txt></Pressable>)}</View><Txt style={{fontWeight:'700'}}>Actividad</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}>{([['sedentary','Poco'],['light','Ligera'],['moderate','Moderada'],['active','Alta'],['veryActive','Muy alta']] as [Activity,string][]).map(([value,label])=><Pressable key={value} onPress={()=>setActivity(value)} style={{padding:10,borderRadius:14,backgroundColor:activity===value?colors.primary:colors.soft}}><Txt style={{fontSize:12,fontWeight:'700',color:activity===value?'#fff':colors.primary}}>{label}</Txt></Pressable>)}</View>
 <SectionTitle>Objetivo</SectionTitle><View style={{flexDirection:'row',gap:8}}>{([['lose','Perder'],['define','Definir'],['maintain','Mantener']] as [Goal,string][]).map(([value,label])=><Pressable key={value} onPress={()=>setGoal(value)} style={{flex:1,alignItems:'center',padding:11,borderRadius:14,backgroundColor:selectedGoal===value?colors.primary:colors.soft}}><Txt style={{fontSize:12,fontWeight:'700',color:selectedGoal===value?'#fff':colors.primary}}>{label}</Txt></Pressable>)}</View><Field label="Objetivo diario (kcal)" value={calories} onChangeText={setCalories} keyboardType="number-pad"/><View style={{flexDirection:'row',gap:9}}><View style={{flex:1}}><Field label="Proteína (g)" value={protein} onChangeText={setProtein} keyboardType="number-pad"/></View><View style={{flex:1}}><Field label="Carbohidratos (g)" value={carbs} onChangeText={setCarbs} keyboardType="number-pad"/></View></View><Field label="Grasas (g)" value={fat} onChangeText={setFat} keyboardType="number-pad"/><Button title="Guardar cambios" onPress={save}/>
 <SectionTitle>Apariencia</SectionTitle><View style={{flexDirection:'row',gap:8}}>{([['system','Sistema'],['light','Claro'],['dark','Oscuro']] as [ThemeMode,string][]).map(([value,label])=><Pressable key={value} onPress={()=>setTheme(value)} style={{flex:1,alignItems:'center',padding:11,borderRadius:14,backgroundColor:theme===value?colors.primary:colors.soft}}><Txt style={{color:theme===value?'#fff':colors.primary,fontWeight:'700'}}>{label}</Txt></Pressable>)}</View><Txt style={{color:colors.muted}}>Unidades: kilogramos y centímetros · Datos guardados localmente</Txt><Button title="Borrar todos mis datos" secondary onPress={remove}/></Page>;
}
