import { useMemo, useState } from 'react';
import { Alert, View } from 'react-native';
import { Button, Card, Field, Page, SectionTitle, Txt, useColors } from '@/components/ui';
import { calculateProgress } from '@/services/nutrition';
import { useApp } from '@/store/AppProvider';
import { dateKey } from '@/services/date';

export default function Progress(){const {profile,weights,addWeight}=useApp();const colors=useColors();const [weight,setWeight]=useState(String(profile?.weightKg??''));const sorted=useMemo(()=>[...weights].sort((a,b)=>a.date.localeCompare(b.date)),[weights]);const current=sorted.at(-1)?.weightKg??profile?.weightKg??0;const start=sorted[0]?.weightKg??profile?.weightKg??current;const target=profile?.targetWeightKg??current;const progress=calculateProgress(start,current,target);const min=Math.min(...sorted.map(x=>x.weightKg),target,current)-1;const max=Math.max(...sorted.map(x=>x.weightKg),target,current)+1;
 const save=async()=>{const n=Number(weight);if(!Number.isFinite(n)||n<35||n>300){Alert.alert('Peso no válido','Introduce un peso entre 35 y 300 kg.');return;}await addWeight({id:`weight-${Date.now()}`,date:dateKey(),weightKg:n});};
 return <Page><Txt style={{fontSize:29,fontWeight:'800'}}>Tu progreso</Txt><Card><Txt style={{color:colors.muted}}>PESO ACTUAL</Txt><Txt style={{fontSize:38,fontWeight:'800'}}>{current.toFixed(1)} <Txt style={{fontSize:16,color:colors.muted}}>kg</Txt></Txt><Txt style={{color:colors.muted}}>Inicio {start} kg · Objetivo {target} kg</Txt><View style={{height:8,backgroundColor:colors.line,borderRadius:8}}><View style={{height:8,width:`${progress}%`,backgroundColor:colors.primary,borderRadius:8}}/></View><Txt style={{color:colors.primary,fontWeight:'700'}}>{progress}% del camino</Txt></Card><Card><SectionTitle>Evolución del peso</SectionTitle>{sorted.length<2?<Txt style={{color:colors.muted}}>Registra al menos dos pesajes para ver tu evolución. Tus registros se guardan en este dispositivo.</Txt>:<View style={{height:150,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-around',paddingTop:15}}>{sorted.slice(-12).map((item,index)=>{const height=Math.max(12,((item.weightKg-min)/(max-min))*105);return <View key={item.id} style={{alignItems:'center',gap:5,flex:1}}><Txt style={{fontSize:10,color:colors.muted}}>{item.weightKg.toFixed(1)}</Txt><View style={{height,backgroundColor:colors.primary,width:18,borderRadius:8}}/><Txt style={{fontSize:9,color:colors.muted}}>{item.date.slice(5)}</Txt></View>})}</View>}</Card><SectionTitle>Registrar peso</SectionTitle><Field label="Peso de hoy (kg)" value={weight} onChangeText={setWeight} keyboardType="decimal-pad"/><Button title="Guardar peso" onPress={save}/><Txt style={{fontSize:12,color:colors.muted}}>El peso puede fluctuar de forma natural. Observa tendencias, no cambios diarios.</Txt></Page>;
}
